"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╔](bright-black)$fill[╗](bright-black)
[║](bright-black) $character$username$sudo$direnv$directory$git_branch$git_status$git_metrics$nodejs$rust$golang$php$python$lua$cmd_duration$time
[╚](bright-black)$fill[╝](bright-black)
[▶](bold green) """

right_format = ""

[fill]
symbol = "═"
style = "bright-black"

[character]
disabled = false
format = '$symbol'
success_symbol = "🧝"
error_symbol = "🍄"

[username]
show_always = true
style_user = "bold green"
style_root = "bold red"
format = '[$user]($style)'

[sudo]
disabled = false
symbol = "🦉sudo"
style = "bold white"
format = ' [│](bright-black) [$symbol]($style)'

[direnv]
disabled = false
symbol = "🏹env:"
style = "bold white"
allowed_msg = "🍀"
denied_msg = "🍂"
format = ' [│](bright-black) [$symbol$allowed]($style)'

[directory]
style = "bold green"
format = ' [│](bright-black) [🌲$path]($style)'
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = "🧭"
style = "bold yellow"
format = ' [│](bright-black) [$symbol$branch]($style)'

[git_status]
style = "bold yellow"
format = '[$all_status$ahead_behind]($style)'
conflicted = "✖"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
stashed = "$$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[git_metrics]
disabled = false
added_style = "bold green"
deleted_style = "bold red"
format = ' [+$added]($added_style)[-$deleted]($deleted_style)'

[nodejs]
symbol = " "
style = "bold green"
format = ' [│](bright-black) [$symbol($version)]($style)'

[rust]
symbol = " "
style = "bold red"
format = ' [│](bright-black) [$symbol($version)]($style)'

[golang]
symbol = " "
style = "bold cyan"
format = ' [│](bright-black) [$symbol($version)]($style)'

[php]
symbol = " "
style = "bold purple"
format = ' [│](bright-black) [$symbol($version)]($style)'

[python]
symbol = " "
style = "bold yellow"
format = ' [│](bright-black) [$symbol($version)]($style)'

[lua]
symbol = " "
style = "bold blue"
format = ' [│](bright-black) [$symbol($version)]($style)'

[cmd_duration]
min_time = 2_000
style = "bold white"
format = ' [│](bright-black) [⌛$duration]($style)'

[time]
disabled = false
time_format = "%R"
style = "bold white"
format = ' [│](bright-black) [🌅$time]($style)'
